# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_options_window(object):
    def setupUi(self, options_window):
        options_window.setObjectName("options_window")
        options_window.resize(900, 550)
        options_window.setMinimumSize(QtCore.QSize(900, 550))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        options_window.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        options_window.setWindowIcon(icon)
        options_window.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(options_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_16 = QtWidgets.QFrame(self.centralwidget)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(500, 250))
        self.frame_5.setMaximumSize(QtCore.QSize(250, 250))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(3, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(3, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_22 = QtWidgets.QLabel(self.frame_4)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_2.addWidget(self.label_22)
        self.frame_11 = QtWidgets.QFrame(self.frame_4)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setObjectName("frame_11")
        self.formLayout = QtWidgets.QFormLayout(self.frame_11)
        self.formLayout.setContentsMargins(2, 0, 2, 0)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtWidgets.QLabel(self.frame_11)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.chrome_area_label = QtWidgets.QLabel(self.frame_11)
        self.chrome_area_label.setWordWrap(True)
        self.chrome_area_label.setObjectName("chrome_area_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.chrome_area_label)
        self.label_9 = QtWidgets.QLabel(self.frame_11)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.chrome_mission_label = QtWidgets.QLabel(self.frame_11)
        self.chrome_mission_label.setObjectName("chrome_mission_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.chrome_mission_label)
        self.label_10 = QtWidgets.QLabel(self.frame_11)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.chrome_cooldown_label = QtWidgets.QLabel(self.frame_11)
        self.chrome_cooldown_label.setObjectName("chrome_cooldown_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.chrome_cooldown_label)
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.chrome_repeat_label = QtWidgets.QLabel(self.frame_11)
        self.chrome_repeat_label.setObjectName("chrome_repeat_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.chrome_repeat_label)
        self.verticalLayout_2.addWidget(self.frame_11)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_12 = QtWidgets.QFrame(self.frame_6)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.formLayout_5 = QtWidgets.QFormLayout(self.frame_12)
        self.formLayout_5.setContentsMargins(0, 0, 5, 0)
        self.formLayout_5.setHorizontalSpacing(6)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_25 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_25)
        self.label_23 = QtWidgets.QLabel(self.frame_12)
        self.label_23.setObjectName("label_23")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.chrome_area = QtWidgets.QLineEdit(self.frame_12)
        self.chrome_area.setObjectName("chrome_area")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.chrome_area)
        self.label_24 = QtWidgets.QLabel(self.frame_12)
        self.label_24.setObjectName("label_24")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.chrome_mission_num = QtWidgets.QLineEdit(self.frame_12)
        self.chrome_mission_num.setObjectName("chrome_mission_num")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.chrome_mission_num)
        self.chrome_mission_submit = QtWidgets.QPushButton(self.frame_12)
        self.chrome_mission_submit.setObjectName("chrome_mission_submit")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.chrome_mission_submit)
        self.horizontalLayout_2.addWidget(self.frame_12)
        self.frame_3 = QtWidgets.QFrame(self.frame_6)
        self.frame_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_6 = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_28 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_28)
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setObjectName("label_26")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.chrome_cooldown_lower = QtWidgets.QLineEdit(self.frame_3)
        self.chrome_cooldown_lower.setObjectName("chrome_cooldown_lower")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.chrome_cooldown_lower)
        self.label_27 = QtWidgets.QLabel(self.frame_3)
        self.label_27.setObjectName("label_27")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.chrome_cooldown_upper = QtWidgets.QLineEdit(self.frame_3)
        self.chrome_cooldown_upper.setObjectName("chrome_cooldown_upper")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.chrome_cooldown_upper)
        self.chrome_cooldown_submit = QtWidgets.QPushButton(self.frame_3)
        self.chrome_cooldown_submit.setObjectName("chrome_cooldown_submit")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.chrome_cooldown_submit)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_20 = QtWidgets.QFrame(self.frame_4)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_8.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_34 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_8.addWidget(self.label_34)
        self.chrome_repeat = QtWidgets.QLineEdit(self.frame_20)
        self.chrome_repeat.setObjectName("chrome_repeat")
        self.horizontalLayout_8.addWidget(self.chrome_repeat)
        self.chrome_repeat_submit = QtWidgets.QPushButton(self.frame_20)
        self.chrome_repeat_submit.setObjectName("chrome_repeat_submit")
        self.horizontalLayout_8.addWidget(self.chrome_repeat_submit)
        self.verticalLayout_2.addWidget(self.frame_20)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.line = QtWidgets.QFrame(self.frame_5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.frame_13 = QtWidgets.QFrame(self.frame_2)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_13.setObjectName("frame_13")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_13)
        self.formLayout_2.setContentsMargins(2, 0, 2, 0)
        self.formLayout_2.setVerticalSpacing(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_19 = QtWidgets.QLabel(self.frame_13)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.firefox_area_label = QtWidgets.QLabel(self.frame_13)
        self.firefox_area_label.setWordWrap(True)
        self.firefox_area_label.setObjectName("firefox_area_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.firefox_area_label)
        self.label_16 = QtWidgets.QLabel(self.frame_13)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.firefox_mission_label = QtWidgets.QLabel(self.frame_13)
        self.firefox_mission_label.setObjectName("firefox_mission_label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.firefox_mission_label)
        self.label_15 = QtWidgets.QLabel(self.frame_13)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.firefox_cooldown_label = QtWidgets.QLabel(self.frame_13)
        self.firefox_cooldown_label.setObjectName("firefox_cooldown_label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.firefox_cooldown_label)
        self.label_17 = QtWidgets.QLabel(self.frame_13)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.firefox_repeat_label = QtWidgets.QLabel(self.frame_13)
        self.firefox_repeat_label.setObjectName("firefox_repeat_label")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.firefox_repeat_label)
        self.verticalLayout.addWidget(self.frame_13)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_15 = QtWidgets.QFrame(self.frame)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.formLayout_8 = QtWidgets.QFormLayout(self.frame_15)
        self.formLayout_8.setContentsMargins(0, 0, 5, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_33 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_33)
        self.label_31 = QtWidgets.QLabel(self.frame_15)
        self.label_31.setObjectName("label_31")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.firefox_area = QtWidgets.QLineEdit(self.frame_15)
        self.firefox_area.setObjectName("firefox_area")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.firefox_area)
        self.label_32 = QtWidgets.QLabel(self.frame_15)
        self.label_32.setObjectName("label_32")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.firefox_mission_num = QtWidgets.QLineEdit(self.frame_15)
        self.firefox_mission_num.setObjectName("firefox_mission_num")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.firefox_mission_num)
        self.firefox_mission_submit = QtWidgets.QPushButton(self.frame_15)
        self.firefox_mission_submit.setObjectName("firefox_mission_submit")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.firefox_mission_submit)
        self.horizontalLayout.addWidget(self.frame_15)
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.formLayout_7 = QtWidgets.QFormLayout(self.frame_14)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_30 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_30)
        self.label_14 = QtWidgets.QLabel(self.frame_14)
        self.label_14.setObjectName("label_14")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.firefox_cooldown_lower = QtWidgets.QLineEdit(self.frame_14)
        self.firefox_cooldown_lower.setObjectName("firefox_cooldown_lower")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.firefox_cooldown_lower)
        self.label_29 = QtWidgets.QLabel(self.frame_14)
        self.label_29.setObjectName("label_29")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.firefox_cooldown_upper = QtWidgets.QLineEdit(self.frame_14)
        self.firefox_cooldown_upper.setObjectName("firefox_cooldown_upper")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.firefox_cooldown_upper)
        self.firefox_cooldown_submit = QtWidgets.QPushButton(self.frame_14)
        self.firefox_cooldown_submit.setObjectName("firefox_cooldown_submit")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.firefox_cooldown_submit)
        self.horizontalLayout.addWidget(self.frame_14)
        self.verticalLayout.addWidget(self.frame)
        self.frame_21 = QtWidgets.QFrame(self.frame_2)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_9.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_35 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_9.addWidget(self.label_35)
        self.firefox_repeat = QtWidgets.QLineEdit(self.frame_21)
        self.firefox_repeat.setObjectName("firefox_repeat")
        self.horizontalLayout_9.addWidget(self.firefox_repeat)
        self.firefox_repeat_submit = QtWidgets.QPushButton(self.frame_21)
        self.firefox_repeat_submit.setObjectName("firefox_repeat_submit")
        self.horizontalLayout_9.addWidget(self.firefox_repeat_submit)
        self.verticalLayout.addWidget(self.frame_21)
        self.horizontalLayout_4.addWidget(self.frame_2)
        self.horizontalLayout_5.addWidget(self.frame_5)
        self.frame_18 = QtWidgets.QFrame(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_18.sizePolicy().hasHeightForWidth())
        self.frame_18.setSizePolicy(sizePolicy)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_18.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.dropped_lw = QtWidgets.QTableWidget(self.frame_18)
        self.dropped_lw.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.dropped_lw.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.dropped_lw.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.dropped_lw.setObjectName("dropped_lw")
        self.dropped_lw.setColumnCount(3)
        self.dropped_lw.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.dropped_lw.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dropped_lw.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dropped_lw.setHorizontalHeaderItem(2, item)
        self.verticalLayout_7.addWidget(self.dropped_lw)
        self.frame_19 = QtWidgets.QFrame(self.frame_18)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.chrome_dropped_lw = QtWidgets.QPushButton(self.frame_19)
        self.chrome_dropped_lw.setObjectName("chrome_dropped_lw")
        self.horizontalLayout_6.addWidget(self.chrome_dropped_lw)
        self.firefox_dropped_lw = QtWidgets.QPushButton(self.frame_19)
        self.firefox_dropped_lw.setObjectName("firefox_dropped_lw")
        self.horizontalLayout_6.addWidget(self.firefox_dropped_lw)
        self.verticalLayout_7.addWidget(self.frame_19)
        self.horizontalLayout_5.addWidget(self.frame_18)
        self.verticalLayout_6.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.centralwidget)
        self.frame_17.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_7 = QtWidgets.QFrame(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.crafted_lw = QtWidgets.QListWidget(self.frame_7)
        self.crafted_lw.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.crafted_lw.setObjectName("crafted_lw")
        self.verticalLayout_4.addWidget(self.crafted_lw)
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.crafted_bl = QtWidgets.QListWidget(self.frame_7)
        self.crafted_bl.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.crafted_bl.setObjectName("crafted_bl")
        self.verticalLayout_4.addWidget(self.crafted_bl)
        self.horizontalLayout_7.addWidget(self.frame_7)
        self.line_2 = QtWidgets.QFrame(self.frame_17)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        self.frame_8 = QtWidgets.QFrame(self.frame_17)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout.setContentsMargins(0, 0, 3, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_10)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 2, 1, 1)
        self.recipe = QtWidgets.QTreeWidget(self.frame_10)
        self.recipe.setMinimumSize(QtCore.QSize(272, 0))
        self.recipe.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.recipe.setObjectName("recipe")
        self.gridLayout.addWidget(self.recipe, 1, 0, 1, 1)
        self.basic_items = QtWidgets.QListWidget(self.frame_10)
        self.basic_items.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.basic_items.setObjectName("basic_items")
        self.gridLayout.addWidget(self.basic_items, 1, 1, 1, 1)
        self.areas = QtWidgets.QListWidget(self.frame_10)
        self.areas.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.areas.setObjectName("areas")
        self.gridLayout.addWidget(self.areas, 1, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_3.setContentsMargins(0, 6, 3, 0)
        self.horizontalLayout_3.setSpacing(12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chrome_pin = QtWidgets.QPushButton(self.frame_9)
        self.chrome_pin.setObjectName("chrome_pin")
        self.horizontalLayout_3.addWidget(self.chrome_pin)
        self.firefox_pin = QtWidgets.QPushButton(self.frame_9)
        self.firefox_pin.setObjectName("firefox_pin")
        self.horizontalLayout_3.addWidget(self.firefox_pin)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.horizontalLayout_7.addWidget(self.frame_8)
        self.verticalLayout_6.addWidget(self.frame_17)
        options_window.setCentralWidget(self.centralwidget)
        self.create_delete_button = QtWidgets.QAction(options_window)
        self.create_delete_button.setObjectName("create_delete_button")
        self.actionf = QtWidgets.QAction(options_window)
        self.actionf.setObjectName("actionf")
        self.actiong = QtWidgets.QAction(options_window)
        self.actiong.setObjectName("actiong")
        self.set_directory_button = QtWidgets.QAction(options_window)
        self.set_directory_button.setObjectName("set_directory_button")
        self.refresh_button = QtWidgets.QAction(options_window)
        self.refresh_button.setObjectName("refresh_button")
        self.scan_button = QtWidgets.QAction(options_window)
        self.scan_button.setObjectName("scan_button")
        self.backup_button = QtWidgets.QAction(options_window)
        self.backup_button.setObjectName("backup_button")
        self.load_button = QtWidgets.QAction(options_window)
        self.load_button.setObjectName("load_button")
        self.edit_action = QtWidgets.QAction(options_window)
        self.edit_action.setObjectName("edit_action")
        self.delete_action = QtWidgets.QAction(options_window)
        self.delete_action.setObjectName("delete_action")
        self.clear_filter_action = QtWidgets.QAction(options_window)
        self.clear_filter_action.setObjectName("clear_filter_action")

        self.retranslateUi(options_window)
        QtCore.QMetaObject.connectSlotsByName(options_window)

    def retranslateUi(self, options_window):
        _translate = QtCore.QCoreApplication.translate
        options_window.setWindowTitle(_translate("options_window", "Options"))
        self.label_3.setText(_translate("options_window", "Chrome Options"))
        self.label_22.setText(_translate("options_window", "Current Config"))
        self.label_8.setText(_translate("options_window", "area url"))
        self.chrome_area_label.setText(_translate("options_window", "lorem ipsum"))
        self.label_9.setText(_translate("options_window", "mission #"))
        self.chrome_mission_label.setText(_translate("options_window", "lorem ipsum"))
        self.label_10.setText(_translate("options_window", "cooldown"))
        self.chrome_cooldown_label.setText(_translate("options_window", "lorem ipsum"))
        self.label_11.setText(_translate("options_window", "repeat"))
        self.chrome_repeat_label.setText(_translate("options_window", "lorem ipsum"))
        self.label_25.setText(_translate("options_window", "World Mission"))
        self.label_23.setText(_translate("options_window", "area url"))
        self.label_24.setText(_translate("options_window", "mission #"))
        self.chrome_mission_submit.setText(_translate("options_window", "submit"))
        self.label_28.setText(_translate("options_window", "Cooldown"))
        self.label_26.setText(_translate("options_window", "lower"))
        self.label_27.setText(_translate("options_window", "upper"))
        self.chrome_cooldown_submit.setText(_translate("options_window", "submit"))
        self.label_34.setText(_translate("options_window", "Repeat"))
        self.chrome_repeat_submit.setText(_translate("options_window", "submit"))
        self.label_4.setText(_translate("options_window", "Firefox Options"))
        self.label_21.setText(_translate("options_window", "Current Config"))
        self.label_19.setText(_translate("options_window", "area url"))
        self.firefox_area_label.setText(_translate("options_window", "lorem ipsum"))
        self.label_16.setText(_translate("options_window", "mission #"))
        self.firefox_mission_label.setText(_translate("options_window", "lorem ipsum"))
        self.label_15.setText(_translate("options_window", "cooldown"))
        self.firefox_cooldown_label.setText(_translate("options_window", "lorem ipsum"))
        self.label_17.setText(_translate("options_window", "repeat"))
        self.firefox_repeat_label.setText(_translate("options_window", "lorem ipsum"))
        self.label_33.setText(_translate("options_window", "World Mission"))
        self.label_31.setText(_translate("options_window", "area url"))
        self.label_32.setText(_translate("options_window", "mission #"))
        self.firefox_mission_submit.setText(_translate("options_window", "submit"))
        self.label_30.setText(_translate("options_window", "Cooldown"))
        self.label_14.setText(_translate("options_window", "lower"))
        self.label_29.setText(_translate("options_window", "upper"))
        self.firefox_cooldown_submit.setText(_translate("options_window", "submit"))
        self.label_35.setText(_translate("options_window", "Repeat"))
        self.firefox_repeat_submit.setText(_translate("options_window", "submit"))
        self.label_12.setText(_translate("options_window", "Dropped LWs"))
        item = self.dropped_lw.horizontalHeaderItem(0)
        item.setText(_translate("options_window", "Name"))
        item = self.dropped_lw.horizontalHeaderItem(1)
        item.setText(_translate("options_window", "Location"))
        item = self.dropped_lw.horizontalHeaderItem(2)
        item.setText(_translate("options_window", "Drop %"))
        self.chrome_dropped_lw.setText(_translate("options_window", "set chrome mission"))
        self.firefox_dropped_lw.setText(_translate("options_window", "set firefox mission"))
        self.label.setText(_translate("options_window", "LWs"))
        self.label_7.setText(_translate("options_window", "BLs"))
        self.label_2.setText(_translate("options_window", "Recipe"))
        self.label_5.setText(_translate("options_window", "Expanded"))
        self.label_6.setText(_translate("options_window", "Total Basic Items"))
        self.label_13.setText(_translate("options_window", "Required Area Access"))
        self.recipe.headerItem().setText(0, _translate("options_window", "Item"))
        self.recipe.headerItem().setText(1, _translate("options_window", "Amount"))
        self.chrome_pin.setText(_translate("options_window", "pin to chrome"))
        self.firefox_pin.setText(_translate("options_window", "pin to firefox"))
        self.create_delete_button.setText(_translate("options_window", "Create and Delete"))
        self.actionf.setText(_translate("options_window", "f"))
        self.actiong.setText(_translate("options_window", "g"))
        self.set_directory_button.setText(_translate("options_window", "Set Directory"))
        self.refresh_button.setText(_translate("options_window", "Refresh"))
        self.scan_button.setText(_translate("options_window", "Scan Directory"))
        self.backup_button.setText(_translate("options_window", "Backup Database"))
        self.load_button.setText(_translate("options_window", "Load Backup"))
        self.edit_action.setText(_translate("options_window", "Edit"))
        self.delete_action.setText(_translate("options_window", "Delete"))
        self.clear_filter_action.setText(_translate("options_window", "Clear Filter"))
